### ISSUE TITLE
[Suggestion] Add a config file to adjust the compass position

### ISSUE THREAD

**Issue by BoredKevin** [iwotastic/IwotasticsCompassMod#1]
Hi, I maintain a modpack called [LethalExpansions](https://thunderstore.io/c/lethal-company/p/goodCompany/LethalExpansions_Modpack/) and one of the mods are [LCBetterClock](https://thunderstore.io/c/lethal-company/p/BlueAmulet/LCBetterClock/), unfortunately, after the v1.2.0 update the BetterClock HUD is overlaid by the compass.

It would be nice for this mod to have a config feature that allows to change the compass's position to be lowered like in the previous version. Currently, the only workaround is to lower the clock which would not be ideal because it blocks visibility a lot.

![image](https://github.com/iwotastic/IwotasticsCompassMod/assets/107290249/e964bfc2-2731-4a9f-aed4-ea1d8dec3047)

**Comment by ProfX66** [comment]
I was just coming here to say the same thing, it looks like it would be easy to implement a config boolean that disables the clock position changes.

**Comment by Entity378** [comment]
> Hi, I maintain a modpack called [LethalExpansions](https://thunderstore.io/c/lethal-company/p/goodCompany/LethalExpansions_Modpack/) and one of the mods are [LCBetterClock](https://thunderstore.io/c/lethal-company/p/BlueAmulet/LCBetterClock/), unfortunately, after the v1.2.0 update the BetterClock HUD is overlaid by the compass.
> 
> It would be nice for this mod to have a config feature that allows to change the compass's position to be lowered like in the previous version. Currently, the only workaround is to lower the clock which would not be ideal because it blocks visibility a lot.
> 
> ![image](https://private-user-images.githubusercontent.com/107290249/296256499-e964bfc2-2731-4a9f-aed4-ea1d8dec3047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzA1MjUsIm5iZiI6MTcwNTQzMDIyNSwicGF0aCI6Ii8xMDcyOTAyNDkvMjk2MjU2NDk5LWU5NjRiZmMyLTI3MzEtNGE5Zi1hZWQ0LWVhMWQ4ZGVjMzA0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxODM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjU5Mzg2OGI0MjNkOGNkYmI1NzgwYjFlZDg0YzUyNGExMmYzYzlhNzhhNGNhMTQ4NzYyZDgxZjI5OTk0NjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yI6bqT2ic57UpDSi4mEJFgEtu6m4SUtn6uOSkoZiPT4)

#2 This should work, as long as the creator of the mod approves my PR or not you can use [my version.](https://github.com/Entity378/IwotasticsCompassModV2/releases/tag/Release-v1.2.1)
